version: "3"

services:
  postgres:
    image: postgres:alpine
    container_name: pix_reaction_db
    environment:
      POSTGRES_USER: pix_user
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - /data/pix_reaction_db:/docker-entrypoint-initdb.d/
    networks:
      - overlay
    ports:
      - "5430:5430"
    command: -p 5430

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pix_frontend
    ports:
      - "5173:5173"
    networks:
      - overlay
volumes:
  postgres-db:

networks:
  overlay:
